name: cubos_widgets
description: Flutter package containing the most used Widgets in Cubos Tecnologia's projects.
version: 1.4.3
homepage: https://github.com/daniloapr/cubos_widgets

publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.18
  flutter_masked_text:
    git:
      url: git://github.com/gabriel-oliveira800/flutter-masked-text
      ref: master # branch name

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
